# Generated by Django 5.2.3 on 2025-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.CharField(blank=True),
        ),
    ]
